### ISSUE TITLE
TFT LCD ILI9488 is not displaying correct image

### ISSUE THREAD

**Issue by titusece** [jaretburkett/ILI9488#3]
![lcd_display](https://user-images.githubusercontent.com/973452/33668668-6e1ca9f0-dac6-11e7-8ef7-43e14735e692.png)

Hello,
I am trying to interface the ILI9488 (320x480) 4 wire SPI LCD display (IM0, IM1, IM2 -> 111) into ARM board which boots Linux OS.
And using FBTFT driver for that.
https://github.com/notro/fbtft
I have created a driver for ILI9488 based on the above driver base and also I have added your init code.
Now I can see some thing on my LCD display but not correct image and you mentioned that ILI9488 doesn't supports 16bit mode (but data sheet mentioned that it supports) but 24bit mode.

What could be the problem ?
Can you please help me out on this ?

https://www.dropbox.com/s/d4lpuefnl98j473/problem-warp-display.webm?dl=0

Attached driver.

[fb_ili9488_ER-TFT035-6.zip](https://github.com/jaretburkett/ILI9488/files/1535738/fb_ili9488_ER-TFT035-6.zip)

LCD:
http://www.buydisplay.com/download/manual/ER-TFT035-6_Datasheet.pdf

Thanks!

**Comment by jaretburkett** [comment]
This has nothing to do with this library.

**Comment by titusece** [comment]
Please refer to the below link for fix.
https://github.com/notro/fbtft/issues/490#issuecomment-350557428
